name: 'Java CI'
on: ['push', 'pull_request']
jobs:

  build:

    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:

      - name: 'Checkout'
        uses: 'actions/checkout@v4' # https://github.com/marketplace/actions/checkout

      - name: 'Gradle Wrapper Validation'
        uses: 'gradle/actions/wrapper-validation@v3' # https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md#usage

      - name: 'Setup Java JDK'
        uses: 'actions/setup-java@v4' # https://github.com/marketplace/actions/setup-java-jdk
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'

      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v3' # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#general-usage
        with:
          gradle-version: 'wrapper'

      - name: 'Execute Gradle'
        run: './gradlew build --warning-mode=all'
