name: "Verify"
on: [push, pull_request]

jobs:
  ci:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 18 # Until Gradle supports Java 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3
      - name: Execute Gradle build
        run: ./gradlew build
