name: 'Java CI'
on: ['push', 'pull_request']
jobs:

  build:

    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:

      - name: 'Checkout'
        uses: 'actions/checkout@v3' # https://github.com/marketplace/actions/checkout

      - name: 'Gradle Wrapper Validation'
        uses: 'gradle/wrapper-validation-action@v1' # https://github.com/marketplace/actions/gradle-wrapper-validation

      - name: 'Setup Java JDK'
        uses: 'actions/setup-java@v3' # https://github.com/marketplace/actions/setup-java-jdk
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'

      - name: 'Execute Gradle'
        uses: 'gradle/gradle-build-action@v2' # https://github.com/marketplace/actions/gradle-build-action
        with:
          gradle-version: 'wrapper'
          arguments: 'build --warning-mode=all'
